version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "container"
    directory: "/container"
    schedule:
      interval: "weekly"
    registry-url: "docker.io"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
