name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36.0.8

  build_project:
    name: Build project
    runs-on: ubuntu-latest

    needs: changelog
    if: |
      contains(needs.changelog.outputs.changelog, 'src') ||
      contains(needs.changelog.outputs.changelog, 'proto')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Build project
        run: PKG_MANAGER=apt make all

  release_version:
    name: Release version
    runs-on: ubuntu-latest

    needs: build_project
    if: |
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, 'Release')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: tagging
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          token: ${{ secrets.PAT }}
